services:
  frontend:
    build: ./frontend
    container_name: orbitonx_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: pnpm dev --host 0.0.0.0

  backend:
    build: ./backend
    container_name: orbitonx_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    env_file:
      - ./backend/.env
    # --- Ithu add cheyyuka ---
    command: npm run dev

  mongo:
    image: mongo:7
    container_name: orbitonx_mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: strongpassword
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: orbitonx_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mongo_data:
  redis_data: