import { PDFParse } from "pdf-parse";
import {
  QUIZ_CATEGORIES,
  QUIZ_DIFFICULTIES,
  normalizeQuestionInput,
} from "../validators/quizAdminValidator.js";

const QUESTION_PREFIX_CLEANUP_REGEX =
  /^(?:(?:question|q)\s*)?\d+\s*[\).:-]?\s*/i;

const QUESTION_START_PATTERNS = [
  /^\d+\s*[\).:-]\s+.+/i,
  /^q\s*\d+\s*[\).:-]?\s+.+/i,
  /^question\s*\d+\s*[\).:-]?\s+.+/i,
  /^\d+\)\s+.+/i,
];
const EXPLICIT_QUESTION_START_REGEX =
  /^(?:q\s*\d+|question\s*\d+)\s*[\).:-]?\s+.+/i;
const PLAIN_NUMBERED_LINE_REGEX = /^(\d+)\s*[\).:-]\s+(.+)$/;

const ALPHA_OPTION_REGEX =
  /^\(?([A-Da-d])\)?\s*[\).:-]\s*(.+)$/;
const NUMERIC_OPTION_REGEX =
  /^\(?([1-4])\)?\s*[\).:-]\s*(.+)$/;
const OPTION_PREFIX_REGEX =
  /^option\s*([A-Da-d1-4])\s*[\).:-]\s*(.+)$/i;
const INLINE_ALPHA_OPTIONS_REGEX =
  /\b([A-Da-d])\s*[\).:-]\s*(.+?)(?=\s+[A-Da-d]\s*[\).:-]\s+|$)/g;

const ANSWER_LINE_REGEX =
  /^(?:ans(?:wer)?|correct\s*answer|correct\s*option)\s*[:\-]\s*(.+)$/i;
const EXPLANATION_LINE_REGEX =
  /^(?:explanation|exp|reason)\s*[:\-]\s*(.+)$/i;
const DIFFICULTY_LINE_REGEX =
  /^difficulty\s*[:\-]\s*(easy|medium|advanced)\s*$/i;
const CATEGORY_LINE_REGEX = /^category\s*[:\-]\s*(.+)$/i;
const TITLE_LINE_REGEX = /^title\s*[:\-]\s*(.+)$/i;
const DESCRIPTION_LINE_REGEX = /^description\s*[:\-]\s*(.+)$/i;
const TIME_LIMIT_LINE_REGEX =
  /^time\s*limit\s*[:\-]\s*(\d+)\s*(?:sec(?:onds?)?)?$/i;
const XP_LINE_REGEX = /^xp(?:\s*potential)?\s*[:\-]\s*(\d+)$/i;

const BULLET_OPTION_REGEX = /^[-*\u2022]\s*(.+)$/;

const PAGE_NUMBER_REGEX =
  /^(?:page\s*)?\d+\s*(?:\/|of)?\s*\d*$/i;
const SEPARATOR_REGEX = /^[-_=~*]{3,}$/;
const COPYRIGHT_REGEX =
  /^(?:copyright|all rights reserved|printed by|generated by)\b/i;
const URL_OR_DOMAIN_REGEX =
  /(?:https?:\/\/|www\.|\b[a-z0-9-]+\.(?:com|org|net|io|in|edu|gov)\b)/i;

const SCANNED_WARNING =
  "This PDF may be image-based or scanned. Text extraction returned little or no readable content.";
export const OCR_FALLBACK_USED_WARNING =
  "OCR fallback was used because direct PDF text extraction was weak or unavailable.";
export const UNREADABLE_SCANNED_PDF_MESSAGE =
  "This PDF appears to be image-based or unreadable. No valid text could be extracted.";

const OCR_MAX_PAGES = 12;
const OCR_DESIRED_WIDTH = 1800;
const QUESTION_MARKER_REGEX = /\b(?:question|answer|correct|option|explanation)\b/gi;
const QUESTION_START_HINT_REGEX =
  /(?:^|\n)\s*(?:q\s*\d+|question\s*\d+|\d+\s*[\).:-])\s+/gim;

const normalizeWhitespace = (value) =>
  String(value || "")
    .replace(/\r\n?/g, "\n")
    .replace(/\t/g, " ")
    .replace(/[ ]{2,}/g, " ")
    .replace(/\u00A0/g, " ")
    .trim();

const normalizeLine = (value) =>
  String(value || "")
    .replace(/[ ]{2,}/g, " ")
    .trim();

const countMatches = (value, regex) => {
  const matches = String(value || "").match(regex);
  return Array.isArray(matches) ? matches.length : 0;
};

const toComparable = (value) =>
  String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");

const buildTextStrengthScore = (text) => {
  const normalized = normalizeWhitespace(text);
  if (!normalized) return 0;

  const lineCount = normalized
    .split("\n")
    .map((line) => normalizeLine(line))
    .filter(Boolean).length;
  const alphaCount = countMatches(normalized, /[A-Za-z]/g);
  const markerCount = countMatches(normalized, QUESTION_MARKER_REGEX);
  const questionStartCount = countMatches(normalized, QUESTION_START_HINT_REGEX);

  return alphaCount + lineCount * 6 + markerCount * 18 + questionStartCount * 25;
};

const isWeakExtractedQuizText = (text) => {
  const normalized = normalizeWhitespace(text);
  if (!normalized) return true;

  const lineCount = normalized
    .split("\n")
    .map((line) => normalizeLine(line))
    .filter(Boolean).length;
  const alphaCount = countMatches(normalized, /[A-Za-z]/g);

  if (lineCount < 4 || alphaCount < 50) {
    return true;
  }

  return buildTextStrengthScore(normalized) < 230;
};

let cachedTesseractCreateWorkerPromise = null;

const loadTesseractCreateWorker = async () => {
  if (cachedTesseractCreateWorkerPromise) {
    return cachedTesseractCreateWorkerPromise;
  }

  cachedTesseractCreateWorkerPromise = (async () => {
    try {
      const module = await import("tesseract.js");
      return module?.createWorker || module?.default?.createWorker || null;
    } catch {
      return null;
    }
  })();

  return cachedTesseractCreateWorkerPromise;
};

const cleanQuestionLine = (line) =>
  line.replace(QUESTION_PREFIX_CLEANUP_REGEX, "").trim();

const parseDifficultyValue = (value, fallback = "Easy") => {
  const normalized = String(value || "").trim();
  if (!normalized) return fallback;

  const difficulty =
    normalized[0].toUpperCase() + normalized.slice(1).toLowerCase();
  return QUIZ_DIFFICULTIES.includes(difficulty) ? difficulty : fallback;
};

const parseCategoryValue = (value, fallback = "JavaScript") => {
  const normalized = String(value || "").trim();
  if (!normalized) return fallback;

  const exact = QUIZ_CATEGORIES.find(
    (category) => category.toLowerCase() === normalized.toLowerCase(),
  );

  return exact || fallback;
};

const looksLikeQuestionStart = (line) => {
  const normalized = normalizeLine(line);
  return QUESTION_START_PATTERNS.some((pattern) => pattern.test(normalized));
};

const looksLikeExplicitQuestionStart = (line) =>
  EXPLICIT_QUESTION_START_REGEX.test(normalizeLine(line));

const getLeadingNumberFromLine = (line) => {
  const match = normalizeLine(line).match(PLAIN_NUMBERED_LINE_REGEX);
  if (!match) return null;
  const parsed = Number.parseInt(match[1], 10);
  return Number.isInteger(parsed) ? parsed : null;
};

const isMetadataLine = (line) =>
  TITLE_LINE_REGEX.test(line) ||
  DESCRIPTION_LINE_REGEX.test(line) ||
  CATEGORY_LINE_REGEX.test(line) ||
  DIFFICULTY_LINE_REGEX.test(line) ||
  TIME_LIMIT_LINE_REGEX.test(line) ||
  XP_LINE_REGEX.test(line);

const isStructuredLine = (line) =>
  looksLikeQuestionStart(line) ||
  ALPHA_OPTION_REGEX.test(line) ||
  NUMERIC_OPTION_REGEX.test(line) ||
  OPTION_PREFIX_REGEX.test(line) ||
  ANSWER_LINE_REGEX.test(line) ||
  EXPLANATION_LINE_REGEX.test(line) ||
  DIFFICULTY_LINE_REGEX.test(line) ||
  isMetadataLine(line);

const isLikelyNoiseLine = (line) => {
  if (!line) return true;
  if (SEPARATOR_REGEX.test(line)) return true;
  if (PAGE_NUMBER_REGEX.test(line)) return true;
  if (COPYRIGHT_REGEX.test(line)) return true;
  if (URL_OR_DOMAIN_REGEX.test(line) && !isStructuredLine(line)) return true;
  return false;
};

const shouldTreatAsRepeatedNoise = (line) => {
  if (!line) return false;
  if (isStructuredLine(line)) return false;
  if (line.length < 5 || line.length > 120) return false;
  if (SEPARATOR_REGEX.test(line)) return false;
  return true;
};

const collectRepeatedNoiseKeys = (lines) => {
  const frequency = new Map();

  lines.forEach((line) => {
    if (!shouldTreatAsRepeatedNoise(line)) return;

    const key = toComparable(line);
    if (!key) return;

    frequency.set(key, (frequency.get(key) || 0) + 1);
  });

  const repeated = new Set();
  frequency.forEach((count, key) => {
    if (count >= 3) repeated.add(key);
  });

  return repeated;
};

const getLinesFromText = (text) => {
  const normalized = normalizeWhitespace(text).replace(/\f/g, "\n");
  const rawLines = normalized
    .split("\n")
    .map((line) => normalizeLine(line))
    .filter(Boolean);

  if (rawLines.length === 0) {
    return {
      lines: [],
      rawLines: [],
      warnings: [SCANNED_WARNING],
    };
  }

  const repeatedNoiseKeys = collectRepeatedNoiseKeys(rawLines);
  const warnings = [];

  let removedByNoise = 0;
  let removedByRepeat = 0;

  const lines = rawLines.filter((line) => {
    if (isLikelyNoiseLine(line)) {
      removedByNoise += 1;
      return false;
    }

    const key = toComparable(line);
    if (key && repeatedNoiseKeys.has(key)) {
      removedByRepeat += 1;
      return false;
    }

    return true;
  });

  if (removedByNoise > 0) {
    warnings.push(`Filtered ${removedByNoise} noisy line(s).`);
  }

  if (removedByRepeat > 0) {
    warnings.push(`Filtered ${removedByRepeat} repeated header/footer line(s).`);
  }

  const alphaCharCount = lines.join(" ").replace(/[^A-Za-z]/g, "").length;
  if (lines.length < 4 || alphaCharCount < 40) {
    warnings.push(SCANNED_WARNING);
  }

  return {
    lines,
    rawLines,
    warnings,
  };
};

const splitIntoQuestionBlocks = (lines = []) => {
  if (lines.length === 0) {
    return {
      blocks: [],
      preface: [],
    };
  }

  const blocks = [];
  const preface = [];
  let current = [];

  const shouldStartNewBlock = (line, existingBlock) => {
    if (!looksLikeQuestionStart(line)) return false;
    if (existingBlock.length === 0) return true;
    if (looksLikeExplicitQuestionStart(line)) return true;

    const leadingNumber = getLeadingNumberFromLine(line);
    if (!leadingNumber) return true;

    const hasAnswerOrExplanation = existingBlock.some(
      (item) => ANSWER_LINE_REGEX.test(item) || EXPLANATION_LINE_REGEX.test(item),
    );
    if (hasAnswerOrExplanation) return true;

    const alphaOptionCount = existingBlock.filter(
      (item) => ALPHA_OPTION_REGEX.test(item) || OPTION_PREFIX_REGEX.test(item),
    ).length;
    if (alphaOptionCount > 0) return true;

    const numericOptionNumbers = existingBlock
      .map((item) => item.match(NUMERIC_OPTION_REGEX)?.[1])
      .filter(Boolean)
      .map((value) => Number.parseInt(value, 10))
      .filter((value) => Number.isInteger(value));

    if (numericOptionNumbers.length > 0 && leadingNumber >= 1 && leadingNumber <= 4) {
      return false;
    }

    if (
      numericOptionNumbers.length === 0 &&
      leadingNumber >= 1 &&
      leadingNumber <= 4 &&
      existingBlock.length <= 2
    ) {
      return false;
    }

    return true;
  };

  lines.forEach((line) => {
    if (shouldStartNewBlock(line, current)) {
      if (current.length > 0 && looksLikeQuestionStart(current[0])) {
        blocks.push(current);
      } else if (current.length > 0) {
        preface.push(...current);
      }

      current = [line];
      return;
    }

    if (current.length === 0) {
      preface.push(line);
      return;
    }

    current.push(line);
  });

  if (current.length > 0 && looksLikeQuestionStart(current[0])) {
    blocks.push(current);
  } else if (current.length > 0) {
    preface.push(...current);
  }

  return {
    blocks,
    preface,
  };
};

const parseQuizMetadataFromPreface = (
  prefaceLines = [],
  { defaultDifficulty = "Easy", defaultCategory = "JavaScript" } = {},
) => {
  const descriptionLines = [];
  const fallbackLines = [];

  const quizData = {
    title: "",
    description: "",
    category: parseCategoryValue(defaultCategory, "JavaScript"),
    difficulty: parseDifficultyValue(defaultDifficulty, "Easy"),
    xpPotential: 1000,
    timeLimit: 600,
    isActive: false,
  };

  prefaceLines.forEach((line) => {
    const titleMatch = line.match(TITLE_LINE_REGEX);
    if (titleMatch) {
      quizData.title = titleMatch[1].trim();
      return;
    }

    const descriptionMatch = line.match(DESCRIPTION_LINE_REGEX);
    if (descriptionMatch) {
      descriptionLines.push(descriptionMatch[1].trim());
      return;
    }

    const categoryMatch = line.match(CATEGORY_LINE_REGEX);
    if (categoryMatch) {
      quizData.category = parseCategoryValue(categoryMatch[1], quizData.category);
      return;
    }

    const difficultyMatch = line.match(DIFFICULTY_LINE_REGEX);
    if (difficultyMatch) {
      quizData.difficulty = parseDifficultyValue(
        difficultyMatch[1],
        quizData.difficulty,
      );
      return;
    }

    const timeLimitMatch = line.match(TIME_LIMIT_LINE_REGEX);
    if (timeLimitMatch) {
      const parsed = Number.parseInt(timeLimitMatch[1], 10);
      if (Number.isInteger(parsed) && parsed > 0) {
        quizData.timeLimit = parsed;
      }
      return;
    }

    const xpMatch = line.match(XP_LINE_REGEX);
    if (xpMatch) {
      const parsed = Number.parseInt(xpMatch[1], 10);
      if (Number.isInteger(parsed) && parsed >= 0) {
        quizData.xpPotential = parsed;
      }
      return;
    }

    if (!isStructuredLine(line) && line.length >= 6) {
      fallbackLines.push(line);
    }
  });

  if (!quizData.title && fallbackLines.length > 0) {
    quizData.title = fallbackLines[0];
  }

  if (descriptionLines.length > 0) {
    quizData.description = descriptionLines.join(" ").trim();
  } else if (fallbackLines.length > 1) {
    quizData.description = fallbackLines.slice(1, 3).join(" ").trim();
  }

  return quizData;
};

const resolveOptionsFromMaps = (alphaMap, numericMap, lines) => {
  if (alphaMap.size > 0) {
    const ordered = ["A", "B", "C", "D"].map((key) => alphaMap.get(key) || "");
    const labelToOption = new Map(
      ["A", "B", "C", "D"]
        .filter((key) => alphaMap.get(key))
        .map((key) => [key, alphaMap.get(key)]),
    );
    return {
      options: ordered,
      labelToOption,
    };
  }

  if (numericMap.size > 0) {
    const orderedNumeric = ["1", "2", "3", "4"].map(
      (key) => numericMap.get(key) || "",
    );

    const labelToOption = new Map(
      ["1", "2", "3", "4"]
        .filter((key) => numericMap.get(key))
        .map((key, idx) => [String.fromCharCode(65 + idx), numericMap.get(key)]),
    );

    return {
      options: orderedNumeric,
      labelToOption,
    };
  }

  const joined = lines.join(" ");
  const inline = [];
  const seen = new Set();

  for (const match of joined.matchAll(INLINE_ALPHA_OPTIONS_REGEX)) {
    const label = String(match[1] || "").toUpperCase();
    const value = normalizeLine(match[2] || "");
    if (!["A", "B", "C", "D"].includes(label) || !value || seen.has(label)) {
      continue;
    }

    seen.add(label);
    inline.push({ label, value });
  }

  if (inline.length >= 2) {
    const map = new Map(inline.map((item) => [item.label, item.value]));
    const options = ["A", "B", "C", "D"].map((key) => map.get(key) || "");
    return {
      options,
      labelToOption: map,
    };
  }

  const bulletOptions = lines
    .map((line) => line.match(BULLET_OPTION_REGEX))
    .filter(Boolean)
    .map((match) => normalizeLine(match?.[1] || ""))
    .filter(Boolean)
    .slice(0, 4);

  if (bulletOptions.length > 0) {
    const normalized = [...bulletOptions];
    while (normalized.length < 4) normalized.push("");

    const labelToOption = new Map(
      normalized
        .map((value, idx) => [String.fromCharCode(65 + idx), value])
        .filter((entry) => entry[1]),
    );

    return {
      options: normalized,
      labelToOption,
    };
  }

  return {
    options: ["", "", "", ""],
    labelToOption: new Map(),
  };
};

const resolveCorrectAnswer = (answerText, options, labelToOption) => {
  const raw = normalizeLine(answerText);
  if (!raw) return "";

  const optionLabelMatch = raw.match(/\b(?:option\s*)?([A-D])\b/i);
  if (optionLabelMatch) {
    const key = optionLabelMatch[1].toUpperCase();
    const mapped = labelToOption.get(key);
    if (mapped) return mapped;

    const index = key.charCodeAt(0) - 65;
    if (options[index]) return options[index];
  }

  const numberLabelMatch = raw.match(/\b([1-4])\b/);
  if (numberLabelMatch) {
    const index = Number.parseInt(numberLabelMatch[1], 10) - 1;
    if (options[index]) return options[index];
  }

  const cleaned = raw
    .replace(/^option\s*/i, "")
    .replace(/^[A-D1-4]\s*[\).:-]?\s*/i, "")
    .trim();

  if (!cleaned) return "";

  const comparable = toComparable(cleaned);
  if (!comparable) return "";

  const exact = options.find((option) => toComparable(option) === comparable);
  if (exact) return exact;

  const included = options.find((option) => {
    const candidate = toComparable(option);
    return candidate && (candidate.includes(comparable) || comparable.includes(candidate));
  });

  return included || "";
};

const toFourOptions = (options = []) => {
  const normalized = [...options].slice(0, 4).map((item) => normalizeLine(item));
  while (normalized.length < 4) normalized.push("");
  return normalized;
};

const parseSingleQuestionBlock = (lines, index, defaultDifficulty = "Easy") => {
  const alphaOptions = new Map();
  const numericOptions = new Map();
  const questionParts = [];

  let answerText = "";
  let explanation = "";
  let difficulty = defaultDifficulty;
  let activeOptionType = "";
  let activeOptionKey = "";
  let captureExplanation = false;

  for (let lineIndex = 0; lineIndex < lines.length; lineIndex += 1) {
    const line = normalizeLine(lines[lineIndex]);
    if (!line || isLikelyNoiseLine(line)) continue;

    if (lineIndex > 0 && looksLikeQuestionStart(line)) {
      const isExplicitStart = looksLikeExplicitQuestionStart(line);
      const isNumericOptionLike = NUMERIC_OPTION_REGEX.test(line);
      const hasCapturedOption = alphaOptions.size > 0 || numericOptions.size > 0;

      if (
        isExplicitStart ||
        (!isNumericOptionLike &&
          (questionParts.length > 0 ||
            hasCapturedOption ||
            Boolean(answerText) ||
            Boolean(explanation)))
      ) {
        break;
      }
    }

    const difficultyMatch = line.match(DIFFICULTY_LINE_REGEX);
    if (difficultyMatch) {
      difficulty = parseDifficultyValue(difficultyMatch[1], difficulty);
      captureExplanation = false;
      activeOptionType = "";
      activeOptionKey = "";
      continue;
    }

    const answerMatch = line.match(ANSWER_LINE_REGEX);
    if (answerMatch) {
      answerText = answerMatch[1].trim();
      captureExplanation = false;
      activeOptionType = "";
      activeOptionKey = "";
      continue;
    }

    const explanationMatch = line.match(EXPLANATION_LINE_REGEX);
    if (explanationMatch) {
      explanation = explanationMatch[1].trim();
      captureExplanation = true;
      activeOptionType = "";
      activeOptionKey = "";
      continue;
    }

    const prefixedOption = line.match(OPTION_PREFIX_REGEX);
    if (prefixedOption) {
      const key = String(prefixedOption[1] || "").toUpperCase();
      const value = normalizeLine(prefixedOption[2] || "");

      if (/^[A-D]$/.test(key)) {
        alphaOptions.set(key, value);
        activeOptionType = "alpha";
      } else if (/^[1-4]$/.test(key)) {
        numericOptions.set(key, value);
        activeOptionType = "numeric";
      }

      activeOptionKey = key;
      captureExplanation = false;
      continue;
    }

    const alphaOption = line.match(ALPHA_OPTION_REGEX);
    if (alphaOption) {
      const key = String(alphaOption[1] || "").toUpperCase();
      alphaOptions.set(key, normalizeLine(alphaOption[2] || ""));
      activeOptionType = "alpha";
      activeOptionKey = key;
      captureExplanation = false;
      continue;
    }

    const numericOption = line.match(NUMERIC_OPTION_REGEX);
    if (
      numericOption &&
      (alphaOptions.size > 0 || numericOptions.size > 0 || questionParts.length > 0)
    ) {
      const key = String(numericOption[1] || "");
      numericOptions.set(key, normalizeLine(numericOption[2] || ""));
      activeOptionType = "numeric";
      activeOptionKey = key;
      captureExplanation = false;
      continue;
    }

    if (captureExplanation) {
      explanation = `${explanation} ${line}`.trim();
      continue;
    }

    if (activeOptionType === "alpha" && alphaOptions.has(activeOptionKey)) {
      alphaOptions.set(
        activeOptionKey,
        `${alphaOptions.get(activeOptionKey)} ${line}`.trim(),
      );
      continue;
    }

    if (activeOptionType === "numeric" && numericOptions.has(activeOptionKey)) {
      numericOptions.set(
        activeOptionKey,
        `${numericOptions.get(activeOptionKey)} ${line}`.trim(),
      );
      continue;
    }

    if (lineIndex === 0) {
      questionParts.push(cleanQuestionLine(line));
      continue;
    }

    if (alphaOptions.size === 0 && numericOptions.size === 0) {
      questionParts.push(line);
    }
  }

  const questionText = normalizeLine(questionParts.join(" "));
  const optionsResult = resolveOptionsFromMaps(alphaOptions, numericOptions, lines);
  const options = toFourOptions(optionsResult.options);
  const nonEmptyOptions = options.filter(Boolean);

  const question = normalizeQuestionInput({
    q: questionText,
    options,
    correctAnswer: "",
    difficulty: parseDifficultyValue(difficulty, defaultDifficulty),
    explanation,
  });

  question.correctAnswer = resolveCorrectAnswer(
    answerText,
    question.options,
    optionsResult.labelToOption,
  );

  const warnings = [];
  const errors = [];

  if (!question.q) {
    errors.push("Question text could not be detected.");
  }

  if (nonEmptyOptions.length < 2) {
    errors.push("At least two options are required for a usable preview question.");
  } else if (nonEmptyOptions.length < 4) {
    warnings.push(
      `Only ${nonEmptyOptions.length} option(s) detected; remaining option slots were left empty for manual fix.`,
    );
  }

  if (!question.correctAnswer) {
    warnings.push("Correct answer was not detected. Please set it manually before save.");
  }

  const usable = !errors.length;

  return {
    index,
    raw: lines.join("\n"),
    question,
    warnings,
    errors,
    usable,
  };
};

const extractTextWithOcrFromPdfBuffer = async (
  buffer,
  { maxPages = OCR_MAX_PAGES, desiredWidth = OCR_DESIRED_WIDTH } = {},
) => {
  const createWorker = await loadTesseractCreateWorker();
  if (!createWorker) {
    return "";
  }

  const parser = new PDFParse({ data: buffer });
  let worker = null;

  try {
    const screenshotResult = await parser.getScreenshot({
      first: maxPages,
      desiredWidth,
      imageDataUrl: false,
      imageBuffer: true,
    });

    const pages = Array.isArray(screenshotResult?.pages)
      ? screenshotResult.pages
      : [];

    if (pages.length === 0) {
      return "";
    }

    worker = await createWorker("eng");
    const textChunks = [];

    for (const page of pages) {
      const pageData =
        page?.data instanceof Uint8Array
          ? Buffer.from(page.data)
          : Buffer.isBuffer(page?.data)
            ? page.data
            : null;

      if (!pageData || pageData.length === 0) {
        continue;
      }

      const ocrResult = await worker.recognize(pageData);
      const pageText = normalizeWhitespace(ocrResult?.data?.text || "");
      if (pageText) {
        textChunks.push(pageText);
      }
    }

    return normalizeWhitespace(textChunks.join("\n\n"));
  } catch {
    return "";
  } finally {
    if (worker && typeof worker.terminate === "function") {
      try {
        await worker.terminate();
      } catch {}
    }

    try {
      await parser.destroy();
    } catch {}
  }
};

export const extractTextFromPdfBuffer = async (buffer) => {
  if (!buffer || !(buffer instanceof Buffer) || buffer.length === 0) {
    throw new Error("Invalid PDF buffer.");
  }

  const parser = new PDFParse({ data: buffer });

  try {
    const result = await parser.getText({});
    return normalizeWhitespace(result?.text || "");
  } finally {
    await parser.destroy();
  }
};

export const extractQuizTextWithOcrFallback = async (
  buffer,
  { ocrMaxPages = OCR_MAX_PAGES } = {},
) => {
  const directText = await extractTextFromPdfBuffer(buffer);
  const normalizedDirectText = normalizeWhitespace(directText);

  let selectedText = normalizedDirectText;
  let usedOcrFallback = false;
  const warnings = [];

  if (isWeakExtractedQuizText(normalizedDirectText)) {
    warnings.push(SCANNED_WARNING);

    const ocrText = await extractTextWithOcrFromPdfBuffer(buffer, {
      maxPages: ocrMaxPages,
    });
    const normalizedOcrText = normalizeWhitespace(ocrText);

    if (normalizedOcrText) {
      const directScore = buildTextStrengthScore(normalizedDirectText);
      const ocrScore = buildTextStrengthScore(normalizedOcrText);

      if (!normalizedDirectText || ocrScore >= directScore) {
        selectedText = normalizedOcrText;
        usedOcrFallback = true;
        warnings.push(OCR_FALLBACK_USED_WARNING);
      }
    }
  }

  if (!normalizeWhitespace(selectedText)) {
    throw new Error(UNREADABLE_SCANNED_PDF_MESSAGE);
  }

  return {
    text: selectedText,
    usedOcrFallback,
    warnings: [...new Set(warnings.filter(Boolean))],
  };
};

export const parseQuizQuestionsFromText = (
  text,
  { defaultDifficulty = "Easy", defaultCategory = "JavaScript" } = {},
) => {
  const safeDifficulty = QUIZ_DIFFICULTIES.includes(defaultDifficulty)
    ? defaultDifficulty
    : "Easy";
  const safeCategory = QUIZ_CATEGORIES.includes(defaultCategory)
    ? defaultCategory
    : "JavaScript";

  const { lines, warnings: lineWarnings } = getLinesFromText(text);
  const { blocks, preface } = splitIntoQuestionBlocks(lines);

  const quizData = parseQuizMetadataFromPreface(preface, {
    defaultDifficulty: safeDifficulty,
    defaultCategory: safeCategory,
  });

  const questions = [];
  const invalidItems = [];
  const parseWarnings = [...lineWarnings];

  blocks.forEach((block, index) => {
    const parsed = parseSingleQuestionBlock(block, index, safeDifficulty);

    if (parsed.usable) {
      questions.push(parsed.question);
    } else {
      invalidItems.push({
        index,
        raw: parsed.raw,
        errors: parsed.errors,
      });
    }

    parsed.warnings.forEach((warning) => {
      parseWarnings.push(`Question ${index + 1}: ${warning}`);
    });

    if (!parsed.usable && parsed.errors.length > 0) {
      parseWarnings.push(
        `Question ${index + 1} skipped: ${parsed.errors.join(" ")}`,
      );
    }
  });

  const uniqueParseWarnings = [...new Set(parseWarnings.filter(Boolean))];

  return {
    quizData,
    quiz: quizData,
    questions,
    invalidItems,
    parseWarnings: uniqueParseWarnings,
    warnings: uniqueParseWarnings,
    meta: {
      totalDetected: blocks.length,
      validCount: questions.length,
      invalidCount: invalidItems.length,
      parseWarnings: uniqueParseWarnings,
      warnings: uniqueParseWarnings,
    },
  };
};
